### ISSUE TITLE
Lokalizacje nie pojawily sie w historii

### ISSUE THREAD

**Issue by JJayJohnny** [H2BGroup/Anti-theft-GPS-system-App#2]
W przypadku dużej ilości (300) wiadomości z lokalizacjami w kolejce, większość z nich nie była widoczna w historii lokalizacji w aplikacji. Wcześniej sprawdziłem kolejke i te dane tam były.

**Comment by JJayJohnny** [comment]
Please fix

**Comment by Hunrax** [comment]
![image](https://github.com/user-attachments/assets/8953e8fb-d149-4463-b69d-eb6fcb1a5cb4)
dalej rzuca jakies wyjatki z "not mounted", nawet po dodaniu tego warunku if(mounted), nie wiem o co chodzi, ale raczej jest to  cos zwiazanego z historią lokalizacji imo, bo jak testowalem wersje wczesniejsze to sie tak nie dzialo

**Comment by Hunrax** [comment]
> ![image](https://private-user-images.githubusercontent.com/57354392/375954767-8953e8fb-d149-4463-b69d-eb6fcb1a5cb4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MzQzMTQsIm5iZiI6MTcyODczNDAxNCwicGF0aCI6Ii81NzM1NDM5Mi8zNzU5NTQ3NjctODk1M2U4ZmItZDE0OS00NDYzLWI2OWQtZWI2ZmNiMWE1Y2I0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDExNTMzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwOGM1ZDg5MTc5YTc1MTVlYjBkNGMwNDM0ZTA4NjVhMTUzZGJmNGZmMGU3ZGJmNzA4MGM2NGNhYTAxYThiOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.iKjXA9G759eu11lYaSYsYhN7GsqyXXVZVdssDwUxO1I) dalej rzuca jakies wyjatki z "not mounted", nawet po dodaniu tego warunku if(mounted), nie wiem o co chodzi, ale raczej jest to cos zwiazanego z historią lokalizacji imo, bo jak testowalem wersje wczesniejsze to sie tak nie dzialo

dobra, to chyba fixed
